name: Main
on:
  push:
    branches:
      - "main"
permissions:
  contents: read
  pull-requests: write
env:
  ENVIRONMENT: 'development'
  SCORE_HUMANITEC_VERSION: 0.9.1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: score-spec/setup-score@v2
        with:
          file: score-humanitec
          version: ${{ env.SCORE_HUMANITEC_VERSION }}
      - name: Run Score
        run: |
          score-humanitec delta \
              --retry \
              --deploy \
              --token ${{ secrets.HUMANITEC_TOKEN }} \
              --org ${{ vars.HUMANITEC_ORG }} \
              --app ${{ vars.APP_NAME }} \
              --env ${{ env.ENVIRONMENT }} \
              | tee score_output.json
