name: Pull Request

on:
  push:
    branches: [ "main" ]
    

permissions:
  contents: read
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install score-humanitec
        run: |
          wget https://github.com/score-spec/score-humanitec/releases/download/0.3.0/score-humanitec_0.3.0_linux_amd64.tar.gz
          tar -xvf score-humanitec_0.3.0_linux_amd64.tar.gz
          chmod +x score-humanitec
          mv score-humanitec /usr/local/bin

      - name: Run Score
        run: score-humanitec delta --retry --deploy --token ${{ secrets.HUMANITEC_TOKEN }} --org ${{ vars.HUMANITEC_ORG }} --app ${{ vars.APP_NAME }} --env development | tee score_output.json
